name: EMHASS
description: Energy Management for Home Assistant
url: https://github.com/davidusb-geek/emhass
version: v0.20.0
slug: emhass
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
image: "ghcr.io/geoderp/emhass" #set if use image container repository
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web interface and API
webui: http://[HOST]:[PORT:5000]
map:
  - config:rw
  - share:rw
init: false
hassio_role: default
homeassistant_api: true
ingress: true
ingress_port: 5000
ingress_stream: true
panel_icon: mdi:home-lightning-bolt-outline
panel_title: EMHASS
environment:
  OPTIONS_PATH: "/data/options.json"
  CONFIG_PATH: "/app/config_emhass.yaml"
  DATA_PATH: "/data/"
options:
  data_path: default
schema:
  hass_url: "str?" #optional
  long_lived_token: "password?" #optional
  logging_level: "list(DEBUG|INFO|WARNING|ERROR)?" #optional
  data_path: "list(default|/data/|/share/)?" #optional
  time_zone: "match((\\w+)?(\\/)(\\w+))?" #optional
  Latitude: "float?" #optional
  Longitude: "float?" #optional
  Altitude: "float?" #optional
  solcast_api_key: "password?" #optional
  solcast_rooftop_id: "str?" #optional
  solar_forecast_kwp: "float?" #optional
